# Generated by Django 5.2.4 on 2025-07-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='transaction',
        ),
    ]
