# Generated by Django 5.2.4 on 2025-07-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_category_table_alter_transaction_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='desc',
            new_name='detail',
        ),
    ]
